var users={target:{src:"",src_element:null,admin_names:[],auth_user_names:[],all_user_names:[],debug_text:null,entred:!1},test:{cmd_element:null,admin_element:null,names:[],names_out:null,admins:[],admins_out:null},name_diff:null,admin_diff:null,to_remove:[],to_lower:[],to_higher:[],passwords:{},pass_btn:null,curr_usr:"",final_cmd:[],needed:[],cmd_out:null},script_flag_container=null,script_flags=[{name:"user cmds",default:!0,fnc:create_user_cmds,element:null},{name:"enable firewall",default:!0,fnc:firewall,element:null},{name:"remove nc",default:!0,fnc:nc,element:null},{name:"password policy",default:!0,fnc:pass_policy,element:null}];function firewall(){users.final_cmd.push("netsh.exe advfirewall set allprofiles state on"),users.final_cmd.push("netsh advfirewall set allprofiles firewallpolicy blockinbound,allowoutbound"),users.final_cmd.push("netsh.exe advfirewall set allprofiles settings inboundusernotification enable"),users.final_cmd.push("netsh.exe advfirewall set allprofiles settings unicastresponsetomulticast enable"),users.final_cmd.push("netsh.exe advfirewall set allprofiles logging filename %SystemRoot%\\System32\\LogFiles\\Firewall\\pfirewall.log")}function nc(){users.final_cmd.push("taskkill /IM \u201Cnc\u201D /F"),users.final_cmd.push("del /f C:\\Windows\\nc.exe")}function pass_policy(){users.final_cmd.push("net accounts /MINPWLEN:10 /MAXPWAGE:90 /UNIQUEPW:10")}function copy_usr_cmd(e){navigator.clipboard.writeText("net users")}function copy_admin_cmd(e){navigator.clipboard.writeText("net localgroup administrators")}function copy_pass(){navigator.clipboard.writeText(users.passwords[users.curr_usr])}function copy_final_cmd(){navigator.clipboard.writeText(users.final_cmd.join(" & "))}function load(){setInterval(check,50),users.target.src_element=document.getElementById("in_users"),users.target.debug_text=document.getElementById("debug_text"),users.test.cmd_element=document.getElementById("cmd_src"),users.test.admin_element=document.getElementById("cmd_src_admin"),users.test.names_out=document.getElementById("cmd-names-out"),users.test.admins_out=document.getElementById("cmd-admins-out"),users.admin_diff=document.getElementById("admin-diff"),users.name_diff=document.getElementById("name-diff"),users.pass_btn=document.getElementById("copy-pass-btn"),users.cmd_out=document.getElementById("cmd-out"),script_flag_container=document.getElementById("script-flags");for(let e in script_flags){let n=script_flags[e],l=document.createElement("input");l.type="checkbox",l.checked=n.default,n.element=l,script_flag_container.appendChild(l);let t=document.createElement("label");t.innerText=n.name,script_flag_container.appendChild(t),script_flag_container.appendChild(document.createElement("br"))}}function check(){check_target(users.target),users.pass_btn.value=`Copy Password For: ${users.curr_usr}`,check_cmd_out(users.test),catigorize_usrs(),users.admin_diff.innerText=`TO PROMOTE:
${users.to_higher.join(" ")}

TO DEMOTE:
${users.to_lower.join(" ")}`,users.name_diff.innerText=`TO DELETE:
${users.to_remove.join(" ")}

TO ADD:
${users.needed.join(" ")}`,users.final_cmd=[];for(let e in script_flags){let n=script_flags[e];n.element.checked&&n.fnc()}users.cmd_out.innerText=users.final_cmd.join(" & ")}function catigorize_usrs(){users.to_remove=users.test.names.filter(e=>!users.target.all_user_names.includes(e)),users.needed=users.target.all_user_names.filter(e=>!users.test.names.includes(e)),users.to_higher=users.target.admin_names.filter(e=>!users.test.admins.includes(e)),users.to_lower=users.test.admins.filter(e=>!users.target.admin_names.includes(e))}function create_user_cmds(){let e=users.final_cmd;for(let n in users.to_higher)e.push(`net localgroup administrators /add ${users.to_higher[n]}`);for(let n in users.to_lower)e.push(`net localgroup administrators /delete ${users.to_lower[n]}`);for(let n in users.to_remove)e.push(`net user /delete ${users.to_remove[n]}`),e.push(`rmdir C:\\users\\${users.to_remove[n]} /s /q`)}function check_cmd_out(e){e.names=extract_user_from_net(e.cmd_element.value),e.names_out.innerText="users: "+e.names.join(", "),e.admins=extract_user_from_net(e.admin_element.value),e.admins_out.innerText="admins: "+e.admins.join(", ")}function extract_user_from_net(e){for(var n=[],l=e.split(`
`);l.length&&!l[0].trim().replaceAll("-","");)l.splice(0,1);for(let s in l){if(l[s].toLowerCase().trim()=="the command completed successfully.".substring(0,l[s].length))break;var t=l[s].slice(0,24).trim();t&&n.push(t);var t=l[s].slice(25,49).trim();t&&n.push(t);var t=l[s].slice(50).trim();t&&n.push(t)}let r=[];for(let s in n)["WDAGUtilityAccount","Administrator","DefaultAccount","Guest"].includes(n[s])||r.push(n[s]);return r}function check_target(e){change_src(e)&&parse_target(e,users.passwords)}function change_src(e){let n=e.src_element.value;return e.src==n?!1:(e.src=n,console.log("val changed"),!0)}function parse_target(e,n){var l=e.src,t=l.split(`
`);let r="password:",s="authorized administrators:",d;console.log(t);let a=0;for(;a<t.length;){let i=t[a].trim(),u=i.toLowerCase(),o;i.includes(r)?([i,o]=i.split(r,2),i=i.trim(),o=o.trim(),i?(n[i]=o,t[a]=i,a++):(n[t[a-1]]=o,t.splice(a,1))):u.includes("authorized users:")?(t.splice(a,1),d=a):u==s.slice(s.length-u.length)?t.splice(a,1):i&&(i.endsWith("(you)")&&(i=i.substring(0,i.length-6).trim(),users.curr_usr=i),t[a]=i,a++)}var c=t.slice(0,d),m=t.slice(d,-1);e.entered=!!t,debug_msg(e.debug_text,"Auth Users: "+m.join(", ")+`
 Admins: `+c.join(", ")),e.admin_names=c,e.auth_user_names=m,e.all_user_names=t}function debug_msg(e,n){e.innerText=n}
